[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=php /var/www/html/artisan queue:work redis --sleep=1 --tries=3 --timeout=90 --queue=asq-gate-service-high,asq-gate-service-default,asq-gate-service-low --max-jobs=500 --max-time=3600 --backoff=3
autostart=true
autorestart=true
user=www-data
numprocs=3
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600
stopasagroup=true
killasagroup=true
priority=20

[program:scheduler]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
user=www-data
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasagroup=true
killasagroup=true