user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    server_tokens off;

    resolver 127.0.0.11 valid=10s;

    # Upstreams (Ensure these match your service names in docker-compose)
    # by default uses round-robin for load balancing
    upstream asq_auth_service { 
        server asq-auth-service:9000; 
        least_conn;
    }
    upstream asq_queue_service { 
        server asq-queue-service:9000;
        least_conn;
    }
    upstream asq_gate_service { 
        server asq-gate-service:9000; 
        least_conn;
    }
    upstream asq_notif_service {
        server asq-notif-service:9000;
        least_conn;
    }
    upstream asq_websocket_service {
        server asq-notif-service:8080;
    }

    server {
        listen 80;
        server_name localhost;

        # Increase the max body size for uploads
        client_max_body_size 50M;

        location /auth/ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_pass asq_auth_service;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_buffering off;
        }

        location /queue/ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_pass asq_queue_service;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_buffering off;
        }

        location /notif/ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_pass asq_notif_service;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_buffering off;
        }

        location /api/ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_pass asq_gate_service;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_buffering off;
        }
        
        location /ws/ {
            proxy_pass http://asq_websocket_service/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600;
        }

        # location = / {
        #     return 301 /;
        # }

        # location ^~ /assets/ {
        #     alias /var/www/asq-frontend/dist/assets/;
        #     try_files $uri =404;
        #     expires 1y;
        #     add_header Cache-Control "public, immutable";
        # }

        # location ^~ / {
        #     alias /var/www/asq-frontend/dist/;
        #     index index.html;

        #     # IMPORTANT FIX
        #     try_files $uri $uri/ /index.html;
        # }

        location / {
            root /var/www/asq-frontend/dist;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}